### ISSUE TITLE
unable to read file .yaml - presumably path to the tilematrix limits because I'm installing koala in an unsual way

### ISSUE THREAD

**Issue by Hendler** [PDOK/gokoala#287]
Hello, 

 Want to use Koala as a front for mb tileserver and have a couple of demo tile sets. 
I install locally via a go script, copying the `assets` and `internal` directories into the directory gokoala is run. 

Apologies in advance - I don't know if this is about not getting a useful error message, or that I'm doing something unusual. 

running `gokoala --config-file config/demo.yaml serve --host 0.0.0.0 --port 8181` 

error comes from not finding the right file here:

```
$ tree internal/ogc/tiles/tileMatrixSetLimits/
internal/ogc/tiles/tileMatrixSetLimits/
├── EuropeanETRS89_LAEAQuad.yaml
├── NetherlandsRDNewQuad.yaml
└── WebMercatorQuad.yaml

0 directories, 3 files
```

```
func ReadFile(filePath string) string {
    // ...
    if err != nil {
        log.Fatalf("unable to read file %s", filePath)  // This is the problem!
    }
}
```
My config directory has this one file
```
version: "1.0.0"  #  
title: "  Tile Server"   
serviceIdentifier: "tile-server"   
abstract: "A tile server providing Natural Earth and OSM data"  
baseUrl: "http://localhost:8181"   

# These fields are required based on the example
keywords:
  - "vector tiles"
  - "natural earth"
  - "osm"
lastUpdated: "2025-03-14T12:00:00Z"
license:
  name: "MIT"
  url: "https://opensource.org/licenses/MIT"
support:
  name: "  Tile Server Support"
  email: "support@example.com"
  url: "https://example.com"

# Optional but recommended fields
datasetDetails:
  - name: "Data Sources"
    value: "Natural Earth, OpenStreetMap"

# Add resources section to point to assets
resources:
  directory: "./assets"

# Add available languages
availableLanguages:
  - en
  - nl



ogcApi:
  tiles:
    title: "  Tile Server"
    abstract: "Vector tile service for Natural Earth and OSM data"
    tileServer: "http://localhost:7800"  
    types:
      - vector
    supportedSrs:
      - srs: EPSG:3857
        zoomLevelRange:
          start: 0
          end: 14
      - srs: EPSG:4326
        zoomLevelRange:
          start: 0
          end: 14
    collections:
      - id: "natural_earth"
        title: "Natural Earth Vector Tiles"
        description: "Natural Earth vector tiles containing countries, cities, and geographic features"
        tileMatrixSetLinks:
          - tileMatrixSet: "WebMercatorQuad"
            tileMatrixSetURI: "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad"
      - id: "osm_english_channel"
        title: "OpenStreetMap English Channel"
        description: "English Channel from OpenStreetMap"
        tileMatrixSetLinks:
          - tileMatrixSet: "WebMercatorQuad"
            tileMatrixSetURI: "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad"
 
 
```

This install script works

```
func installGokoala() error {
	// Get current working directory
	currentDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get current directory: %v", err)
	}

	// Create temp directory
	tmpDir, err := os.MkdirTemp("", "gokoala-install")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	fmt.Println("Cloning gokoala repository...")
	cmd := exec.Command("git", "clone", "--depth", "1", "https://github.com/PDOK/gokoala.git", tmpDir)
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to clone gokoala: %v\nOutput: %s", err, output)
	}

	// Install dependencies like in the Dockerfile
	fmt.Println("Installing build dependencies...")
	aptCmd := exec.Command("sudo", "apt-get", "install", "-y",
		"libcurl4-openssl-dev",
		"libssl-dev",
		"libsqlite3-mod-spatialite")
	if output, err := aptCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to install dependencies: %v\nOutput: %s", err, output)
	}

	// Build steps from Dockerfile
	fmt.Println("Building gokoala...")
	buildCmd := exec.Command("go", "mod", "download", "all")
	buildCmd.Dir = tmpDir
	if output, err := buildCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to download dependencies: %v\nOutput: %s", err, output)
	}

	generateCmd := exec.Command("go", "generate", "-v", "./...")
	generateCmd.Dir = tmpDir
	if output, err := generateCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to generate: %v\nOutput: %s", err, output)
	}

	buildCmd = exec.Command("go", "build",
		"-v",
		"-ldflags", "-w -s",
		"-a",
		"-installsuffix", "cgo",
		"-o", "gokoala",
		"github.com/PDOK/gokoala/cmd")
	buildCmd.Dir = tmpDir
	buildCmd.Env = append(os.Environ(),
		"CGO_ENABLED=1",
		"GOOS=linux",
		"GOTOOLCHAIN=go1.23.6")

	if output, err := buildCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to build gokoala: %v\nOutput: %s", err, output)
	}

	fmt.Println("Installing assets and templates...")
	// Create destination directories in current directory
	for _, dir := range []string{"assets", "internal"} {
		destDir := filepath.Join(currentDir, dir)
		if err := os.MkdirAll(destDir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %v", dir, err)
		}
	}

	// Copy directories with all subdirectories preserved
	for _, dir := range []string{"assets", "internal"} {
		sourceDir := filepath.Join(tmpDir, dir)
		destDir := filepath.Join(currentDir, dir)

		// Clean existing directory first
		if err := os.RemoveAll(destDir); err != nil {
			return fmt.Errorf("failed to clean existing directory %s: %v", dir, err)
		}

		// Copy the entire directory structure
		copyCmd := exec.Command("cp", "-r",
			sourceDir, // Source directory (complete path)
			destDir)   // Destination directory (complete path)
		if output, err := copyCmd.CombinedOutput(); err != nil {
			return fmt.Errorf("failed to copy %s: %v\nOutput: %s", dir, err, output)
		}
	}

	// Debug: Print directory structure after copying
	fmt.Println("\nVerifying installed files:")
	lsCmd := exec.Command("ls", "-R", filepath.Join(currentDir, "internal"), filepath.Join(currentDir, "assets"))
	if output, err := lsCmd.CombinedOutput(); err == nil {
		fmt.Printf("Directory structure:\n%s\n", output)
	} else {
		fmt.Printf("Failed to list directory structure: %v\n", err)
	}

	// Install binary
	fmt.Println("Installing binary...")
	copyCmd := exec.Command("sudo", "cp",
		filepath.Join(tmpDir, "gokoala"),
		"/usr/local/bin/gokoala")
	if output, err := copyCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to copy binary: %v\nOutput: %s", err, output)
	}

	chmodCmd := exec.Command("sudo", "chmod", "755", "/usr/local/bin/gokoala")
	if output, err := chmodCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to set permissions: %v\nOutput: %s", err, output)
	}

	fmt.Printf("gokoala installed successfully. Assets and templates installed in %s\n", currentDir)
	return nil
}
```
